services:
  backend:
    image: skeleton:0.1.0
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING.PROFILES.ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      database:
        condition: service_healthy
      session:
        condition: service_healthy

  database:
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: "5s"
      timeout: "5s"
      retries: 5

  session:
    image: redis:7-alpine
    restart: always
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: "5s"
      timeout: "5s"
      retries: 5

volumes:
  postgres_data:
