services:
  database:
    image: postgres:16-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: "5s"
      timeout: "5s"
      retries: 5

  session:
    image: redis:7-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: "5s"
      timeout: "5s"
      retries: 5

  observability:
    image: grafana/otel-lgtm:0.7.2
    ports:
      # OpenTelemetry Collector gRPC endpoint
      - "127.0.0.1:4317:4317"
      # OpenTelemetry Collector HTTP endpoint
      - "127.0.0.1:4318:4318"
      # Grafana UI
      - "127.0.0.1:3000:3000"

volumes:
  postgres_data:
