services:
  database:
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  session:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "127.0.0.1:4318:4318"
      - "127.0.0.1:4317:4317"
    volumes:
      - ./docker/otel-collector/otel-collector.yml:/etc/otelcol-contrib/config.yaml

  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./docker/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml

  loki:
    image: grafana/loki

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/tmp/tempo

volumes:
  postgres_data:
  prometheus_data:
  tempo_data:
