services:
  backend:
    image: skeleton:0.1.0
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING.PROFILES.ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - database
      - session

  database:
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  session:
    image: redis:7-alpine
    restart: always
    expose:
      - "6379"

volumes:
  postgres_data:
