name: CI

on: [push, pull_request]

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: chmod +x gradlew
      - run: ./gradlew test

  fmt:
    name: Spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: chmod +x gradlew
      - run: ./gradlew spotlessCheck
